{{- $serviceName := "sourcegraph-frontend" -}}
{{- $servicePort := 30080 -}}
{{- if .Values.frontend.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- if .Values.frontend.ingress.annotations}}
  annotations:
    {{- toYaml .Values.frontend.ingress.annotations | nindent 4 }}
  {{- end }}
  labels:
    app: sourcegraph-frontend
    deploy: sourcegraph
    app.kubernetes.io/component: frontend
    {{- if .Values.frontend.ingress.labels }}
      {{- toYaml .Values.frontend.ingress.labels | nindent 4 }}
    {{- end }}
  name: {{ .Values.frontend.name }}
spec:
  {{- if and .Values.frontend.ingress.host .Values.frontend.ingress.tlsSecret }}
  tls:
  - hosts:
    - {{ .Values.frontend.ingress.host }}
    secretName: {{ .Values.frontend.ingress.tlsSecret }}
  {{- if .Values.frontend.ingress.extraTLSSecrets }}
  {{- toYaml .Values.frontend.ingress.extraTLSSecrets | nindent 2 }}
  {{- end }}
  {{- end }}
  {{- if .Values.frontend.ingress.host }}
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $serviceName }}
            port:
              number: {{ $servicePort }}
    host: {{ .Values.frontend.ingress.host }}
  {{- range $host := .Values.frontend.ingress.extraHosts }}
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ $serviceName }}
              port:
                number: {{ $servicePort }}
    host: {{ $host }}
  {{- end }}
  {{- end }}
  {{- if .Values.frontend.ingress.ingressClassName }}
  ingressClassName: {{ .Values.frontend.ingress.ingressClassName }}
  {{- end }}
{{- end }}
